[project]
name = "scripts"
version = "0.1.0"
description = "ZKsync OS upgrade scripts."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "packaging>=25.0",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
]

[dependency-groups]
dev = [
    "licensecheck>=2025.1.0",
]
